#!/bin/bash
export TTY

# cd $HOME/go/src/github.com/codelingo/codelingo

dir="$1"
if ! test -d "$dir"; then
    echo "$0 <tenets directory>"
    exit 1
fi

# Ensure tenet dirs are valid (dashes, not underscores)
find "$dir" -name 'codelingo.yaml' | while read fp; do
    dirname "$fp"
done | sort | uniq | while read dn; do
    dn_bn="$(basename "$dn")"
    if ! test "$dn_bn" == "."; then
        dn_dn="$(dirname "$dn")"
        echo "$dn"
        dn_slug="$(printf -- "%s" "$dn_bn" | slugify)"

        good_path="$dn_dn/$dn_slug"

        if test "$dn_bn" != "$dn_slug" && ! test -e "$good_path"; then
            mv "$dn" "$good_path"
        fi
    fi
done

find "$dir" -name 'codelingo.yaml' | while read line; do
    cat "$line" | migrate-codelingo-yaml | sponge "$line";
done
